import * as openapi from './openapi'

export type Link = openapi.types.components['schemas']['Link']
export type Language = openapi.types.components['schemas']['Language']
export type Performer = openapi.types.components['schemas']['Performer']
export type Session = openapi.types.components['schemas']['Session']
export type CustomField = openapi.types.components['schemas']['CustomField']
export type Image = openapi.types.components['schemas']['Image']
export type News = openapi.types.components['schemas']['News']
export type DelayedNews = openapi.types.components['schemas']['DelayedNews']
export type Group = openapi.types.components['schemas']['Group']
export type Venue = openapi.types.components['schemas']['Venue']
export type Day = openapi.types.components['schemas']['Day']
export type VenueCategory = openapi.types.components['schemas']['VenueCategory']
export type VenueCategoryLayout = openapi.types.components['schemas']['VenueCategoryLayout']
export type Highlight = openapi.types.components['schemas']['Highlight']
